### ISSUE TITLE
Add an option for choosing download location

### ISSUE THREAD

**Issue by MrMetternich** [rhadamanthe/host-grabber-pp#50]
Please consider adding an option to alter the download location from the standard "downloads" folder to a different one.

**Comment by rhadamanthe** [comment]
That would be nice, indeed.
Unfortunately, neither Firefox, nor Chrome provide such an option. And we cannot interact with the file system without their API.

One workaround I have not yet tried is about changing the default download location on the fly. But honestly, it means asking the download location every time. And I am not sure it is possible. I let this issue open for the moment.

**Comment by tzr7** [comment]
Your are right that it's not possible to access the file system. But you could create sub-directories in the configured Browser's download folder. Having a separate sub-folder for each run could make organizing easier. To download to a sub folder just add a path to the download target, e.g. 'foo/bar/file.jpg'.

The Browser then downloads to '{user-home}/Downloads/foo/bar' (if '{user-home}/Downloads' is the configured Browser download folder).

**Comment by rhadamanthe** [comment]
OK. I have several enhancements in progress.
I will try to add this feature. Most likely during Christmas hollidays.

**Comment by rhadamanthe** [comment]
Like I said, it is not possibe to select a different download location than the browser's default one.
However, I have added new options to dispatch files in sub-directories. This will be released with the next version, probably in few days.

**Comment by sjgard2001** [comment]
I very much appreciate the work you have done on this extension including adding the option to create download sub-folders covered here. I wasn't sure whether to add this minor enhanced to this new feature here or to add it in a separate request. I'll add the comment here for your consideration as it's very much on-topic.

I'd like to request the option for the download sub-directories to be based on the <title> tag of the page the images are coming from. This was a feature of ImageHost Grabber ("Create a sub-directory with document title inside the target directory") which is particularly useful on forum based sites where images are grouped together in gallery pages. Rather than having every image from a site in a single directory we would end up with one directory per topic as provided in the <title> tag thereby nicely grouping images in context with a descriptive sub-directory name and replicating a function from IHG which I certainly made use of all the time.

Thank you for your time.

**Comment by rhadamanthe** [comment]
@sjgard2001 I have created #58 to address this requirement.
