### ISSUE TITLE
IHG++ does not recognise pimpandhost.com

### ISSUE THREAD

**Issue by igorvolnyi** [rhadamanthe/host-grabber-pp#69]
Example page [Amy Jackson - Page 2](http://www.planetsuzy.org/t893860-p2-amy-jackson.html)

**Comment by rhadamanthe** [comment]
Hi,

I do not manage the catalog for everyone as I have a complicated schedule. However, I can review and integrate contributions. If you want to submit an entry for this host, you are welcome.

[The documentation](https://rhadamanthe.github.io/host-grabber-pp/en/hosts-definition.html) explains what to add to [the catalog](https://github.com/rhadamanthe/host-grabber-pp-host.xml) to test it. There are also [debugging tools](https://rhadamanthe.github.io/host-grabber-pp/en/index.html#debugging) that really simplify the work. I can also help you if you encounter problems or if things need to be explained.

The few time I can give to this project will be about fixing the feature issues, e.g. #65 and #68 .

**Comment by igorvolnyi** [comment]
Will hosts.xml from original IHG work? I can't figure out how to attach it. Tried both from local drive and by download url. But when I press "Reload Dictionary" or "Save Dictionary URL" the option's input turns red and nothing happens.

**Comment by rhadamanthe** [comment]
No, you cannot use IHG's catalog.  
The philosophy behind is the same, but the syntax is slightly different. Options are different. This extensions supports a XPATH strategy while IHG does not. And IHG allows executing arbitrary code (JS functions), which this extension does not (and that Mozilla would not allow).

However, you may find the inspiration in IHG's catalog, for some hosts.  
And it is not possible to reference a local dictionary (`file:/` URLs) because web browsers have security policies to prevent it. The dictionary referenced in the options must be hosted on some web server. #21 aims at managing a local dictionary directly, but not as a user file.
