### ISSUE TITLE
Naming of download file: Add option to prefix file names with position on page

### ISSUE THREAD

**Issue by ghost** [rhadamanthe/host-grabber-pp#79]
This is related to #75:

For some downloads file names are made random by the host. There are cases where the order of files is essential, like comic book pages or image sets. 
It would be nice to have the option to prefix the file names with the index position the image on the page. 
Iinstead of filenames like
```
asdasd.jpg
sasdzz.jpg
zkjuik.jpg
```
the order downloaded could be like
```
000001_zkjuik.jpg
000002_sasdzz.jpg
000003_asdasd.jpg
```

This could be a global option or per download. I would prefer a global option. If I do not want the prefix in a specific download, it can easily be removed afterwards.

Image Host Grabber Classic had a similar feature.

**Comment by rhadamanthe** [comment]
I have thought about adding this feature in the version I have just released.
It is not complicated to have. But I hesitated because some hosts and web sites already sort their images and use pretty names. So, having this feature based on the catalog would make sense too.

Also, we must be aware that images ordering is not built from their position in the page, but from the catalog's ordering. So, with this feature, images would be sorted by web hosts first. In a single post, if all the images are located on the same host, it will work. But if various hosts are used, ordering will not match what is displayed on screen.

I really need to think about the various use cases before coding anything. :)

**Comment by rhadamanthe** [comment]
There are 2 solutions:

1. Have a global option but only apply it to hosts whose catalog entry declare it (e.g. they do not use pretty names).
2. Have a global option but disable it for hosts whose catalog entry declare it (e.g. they use pretty names and already sort files).

The second option is probably the best, as their number seems more limited.
I will add this feature in the next version. The catalog will be updated in consequence for the few hosts that already use pretty names.

**Comment by rhadamanthe** [comment]
Done, as part of a huge rework.
The counter option will be available in the next version. It is not the position in the page, as this extension first groups them by host, but pictures in a same post should be ordered correctly thanks to this feature.
